---
name: "Build and tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cmakelists-version:
    uses: froglets/flappy-frog/.github/workflows/_parse_version.yml@master
    with:
      github_sha: ${{ github.sha }}

  ci-release:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu16.04:1.46.2
    needs:
      cmakelists-version
    uses: froglets/flappy-frog/.github/workflows/_build.yml@master
    with:
      library_name: ${{ github.event.repository.name }}
      library_version: ${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}
      github_sha: ${{ github.sha }}
      profile_host: release
      profile_build: release

  ci-ios:
    runs-on: macos-latest
    needs:
      cmakelists-version
    uses: froglets/flappy-frog/.github/workflows/_build.yml@master
    with:
      library_name: ${{ github.event.repository.name }}
      library_version: ${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}
      github_sha: ${{ github.sha }}
      profile_host: ios_simulator_release
      profile_build: release
